apiVersion: v1
kind: Secret
metadata:
  name: openobserve-credentials
  namespace: observability
type: Opaque
stringData:
  OPENOBSERVE_ENDPOINT: "http://openobserve.openobserve.svc.cluster.local:5080"
  OPENOBSERVE_ORG: "default"
  OPENOBSERVE_USERNAME: "admin@xyz.com"
  OPENOBSERVE_PASSWORD: "adminXYZ123!"
